### ISSUE TITLE
Non-carousel additional images don't display

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-BETA-#10]
When Configuration->Product Info->Use Bootstrap Additional Image Carousel is set to 0 (i.e. no carousel), clicking an additional image's "Larger Image" link has no effect.

The behavior can be viewed on the template's demo site here: http://www.zcadditions.com/bootstrap_tpl_demo/index.php?main_page=product_info&cPath=3_13&products_id=8

**Comment by zcadditions** [comment]
I think I figured this one out. Can you re-try the demo to confirm?

**Comment by lat9** [comment]
Confirmed, it is!
