### ISSUE TITLE
Align additional-images with new (zc156) notifiers

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-BETA-#21]
This will enable interoperation with Image Handler 5.0.0 and later.

**Comment by lat9** [comment]
I'm thinking, perhaps, to create an additional ZCA-Bootstrap configuration item that instructs the template whether or not to use its modal display of product images.  That setting could be used, for instance, if a store owner wants to use `bootstrap` along with another popup-image display plugin (e.g. ColorBox).

Any/all comments appreciated.

**Comment by zcadditions** [comment]
I'm thinking it would be a good idea! The modal display for images was so it had an image feature option out of box, then the option to add additional images ie. carousel. But never left an option for "any other" options.

**Comment by badarac** [comment]
Having a configuration variable would be a good solution. I suspect we'll find others that will needed as plugins get modified to use bootstrap.

**Comment by lat9** [comment]
The addition of that configuration setting is going to be a bit tricky, since the configuration settings are currently created when the "base" `bootstrap` template is activated via the admin's _Tools->Template Selection_.

To get the configuration "set", any pre-existing installation (with or without clone) will need to change to template-selection to `bootstrap`.  

- For a site using a `bootstrap` clone, this involves changing back to the "master" version and then back to the clone.
- For a site using the `bootstrap` master, the template will need to be changed to a non-bootstrap one (e.g. `classic`) and then back to `bootstrap` to effect the change.

The above change will need to be documented in the template's readme upon release.

**Comment by badarac** [comment]
I'm not sure I understand. In init_zca_bootstrap the configuration table is updated with new settings if they don't exist. Then it resets values to reflect the bootstrap template and updates some descriptions. Once added, these settings appear regardless of the template used. I see the problem with a non-bootstrap template having that set and referenced though. Is checking for IS_ZCA_BOOTSTRAP_TEMPLATE being defined the way I did a better solution?

**Comment by lat9** [comment]
That initialization script runs (in the admin) _only when_ the `bootstrap` template (the base one) is activated via Tools->Template Selection.  The `IS_ZCA_BOOTSTRAP_TEMPLATE` definition occurs only on the storefront; that's why I'm hesitant to use that definition's presence during admin processing.

**Comment by lat9** [comment]
Initial changes captured.  I'm with @badarac on the installation; I need to give that some thought as to what triggers the configuration-table additions now that there's that language-definition identifying the template as either the master `bootstrap` or a clone thereof.

**Comment by drbyte** [comment]
Can a value in the template_info.php file be leveraged?

**Comment by lat9** [comment]
> Can a value in the template_info.php file be leveraged?

It could, but my conundrum is finding a way that a _single_ definition (or variable) can be used to detect that the ZCA Bootstrap template or one of its clones is being set.  That template_info.php file is (currently) only loaded by the _**Tools->Template Selection**_ processing.

How about:

1. Remove `includes/languages/english/extra_definitions/bootstrap/zca_bootstrap_id.php`.
2. Modify `includes/templates/bootstrap/template_info.php` to contain the definition of `IS_ZCA_BOOTSTRAP_TEMPLATE`.
3. Update `includes/init_includes/init_zca_bootstrap.php` to load, if present, the `template_info.php` for the active template prior to its load of the template-specific function file (since the function uses the presence of that definition to indicate that a bootstrap template is active).
4. Update the template's admin observer to detect the activation of a bootstrap template by loading (if present) the to-be-activated template's template_info.php and checking to see if the common definition is active.

**Comment by drbyte** [comment]
Sometimes a helpful thinking approach is to look at it from another angle: if this was the default template, how would other things have to be altered to indicate they were NOT a clone/derivative?

**Comment by lat9** [comment]
> Can a value in the template_info.php file be leveraged?

It could, but my conundrum is finding a way that a _single_ definition (or variable) can be used to detect that the ZCA Bootstrap template or one of its clones is being set.  That template_info.php file is (currently) only loaded by the _**Tools->Template Selection**_ processing.

How about:

1. Remove `includes/languages/english/extra_definitions/bootstrap/zca_bootstrap_id.php`.
2. Modify `includes/templates/bootstrap/template_info.php` to contain the definition of `IS_ZCA_BOOTSTRAP_TEMPLATE`.
3. Update `includes/init_includes/init_zca_bootstrap.php` to load, if present, the `template_info.php` for the active template prior to its load of the template-specific function file (since the function uses the presence of that definition to indicate that a bootstrap template is active).
4. Update the template's admin observer to detect the activation of a bootstrap template by loading (if present) the to-be-activated template's template_info.php and checking to see if the common definition is active.

**Comment by badarac** [comment]
What about naming the configuration value (title, key, and description) to include the selected template name. Something like Use modal display for images in your_template, USE_MODAL_IMAGE_YOUR_TEMPLATE, description . Then a bootstrap template could build the table and the store side could test for that and create the contents as appropriate. That would mean that every bootstrap template would require the init_includes to add the additional table updates. Which I think will be the case anyway.

**Comment by lat9** [comment]
I've broken the installation "issue" out separately: #24 ... just to keep focus.
