### ISSUE TITLE
Required pulldown menus need col class

### ISSUE THREAD

**Issue by badarac** [zcadditions/ZCA-Bootstrap-Template-BETA-#23]
The pull downs created on forms for required fields have  a minor formatting issue which resulted from bootstrap. It caused the * added to required dropdowns to move to a new line. 
Here's the change I made to includes/classes/observers/ZcaBootstrapObserver.php. It affects all pull downs not just required. 
Here's the change I made to includes/classes/observers/ZcaBootstrapObserver.php. It affects all pull downs not just required. 
```
            case 'NOTIFY_ZEN_DRAW_PULL_DOWN_MENU':
                $field = $p2;
                if (strpos($field, 'class="') !== false) {
                    $field = str_replace('class="', 'class="custom-select col-11', $field);
                } else {
                    $field = str_replace('<select ', '<select class="custom-select col-11" ', $field);
                }
                $p2 = $field;
                break;


```

**Comment by lat9** [comment]
Thanks for the report; I'll review each of those HTML input-field updates to make sure that any pre-existing class is preserved, adding the template's required classes instead of overwriting them!

**Comment by badarac** [comment]
I found an additional  issue related to this which I had fixed. It affected includes/templates/bootstrap/tpl_modules_create_account.php . 
The pull down for the state was creating both the pull down and invisible fields for the text input box when $flag_show_pulldown_states was true.  This took additional space under the state pulldown.  Corrected the if logic to format correctly.
<?php
  if (ACCOUNT_STATE == 'true') {
		if ($flag_show_pulldown_states == true) {
	?>
	<label class="inputLabel" for="stateZone" id="zoneLabel"><?php echo ENTRY_STATE; ?></label>
	<?php
		  echo zen_draw_pull_down_menu('zone_id', zen_prepare_country_zones_pull_down($selected_country), $zone_id, 'id="stateZone"','true');
		  if (zen_not_null(ENTRY_STATE_TEXT)) echo '&nbsp;<span >' . ENTRY_STATE_TEXT . '</span>';
		echo '<div class="p-2"></div>';
	 } else {?>
	<label class="inputLabel" for="state" id="stateLabel"><?php echo $state_field_label; ?></label>
	<?php
		echo zen_draw_input_field('state', '', zen_set_field_length(TABLE_ADDRESS_BOOK, 'entry_state', '40') . ' id="state" placeholder="' . ENTRY_STATE_TEXT . '"');
		if ($flag_show_pulldown_states == false) {
		  echo zen_draw_hidden_field('zone_id', $zone_name, ' ');
		}
	?>
	<div class="p-2"></div>
	<?php
	  }
}
?>

**Comment by lat9** [comment]
The above commit addresses the first issue identified; the second one is "out of my bailiwick".

**Comment by zcadditions** [comment]
I'll take on the second issue.

**Comment by badarac** [comment]
I just looked at the second issue and resolved the formatting issues in my comment by adding code tags. You can now see the entire change in a more readable format. Sorry

**Comment by zcadditions** [comment]
I need to look at the first issue, it doesn't fix the issue on all screen sizes

**Comment by badarac** [comment]
I assume you're referring to the country field. That one is really affected by screen size. This seems to work: 
custom-select col-7 col-sm-8 col-md-10 col-lg-11

**Comment by zcadditions** [comment]
It's also putting the select right of the label on some screen sizes

**Comment by badarac** [comment]
Changing the span with seems to fix it at all screen sizes by making the padding 0
`(zen_not_null(ENTRY_COUNTRY_TEXT) ? '<span class="alert p-0">' . ENTRY_COUNTRY_TEXT . '</span>': ''); ?>`

**Comment by lat9** [comment]
Let me know if that observer-class needs update!

**Comment by badarac** [comment]
It looks like this was not completely fixed. I can see that the alert has been moved to the label on the state field but it was not on the country. 
![capture](https://user-images.githubusercontent.com/6716614/37975266-edc8a590-31ac-11e8-86ec-81376940c411.JPG)

**Comment by zcadditions** [comment]
Yea, I noticed it as well when doing a clean install. I'll reopen this issue, provide the fix here on git and include it in the next release.
