### ISSUE TITLE
More information appears in the hamburger menu 

### ISSUE THREAD

**Issue by badarac** [zcadditions/ZCA-Bootstrap-Template-BETA-#29]
More information appears in the hamburger menu even though EZPAGES_STATUS_SIDEBOX is turned off. What I found was the if logic was executed after the beginning of the list item . I moved the check and it now works correctly. The edit is to includes/templates/bootstrap/tpl_offcanvas_menu.php. It also might be helpful to change the title and description for the config value to indicate that it controls the display in the hamburger menu as well. 
`<?php	  
  // test if sidebox should display
  if (EZPAGES_STATUS_SIDEBOX == '1' or (EZPAGES_STATUS_SIDEBOX== '2' and (strstr(EXCLUDE_ADMIN_IP_FOR_MAINTENANCE, $_SERVER['REMOTE_ADDR'])))) {
    if (isset($var_linksList)) {
      unset($var_linksList);
    }	?>
      <li class="nav-item dropdown d-lg-none">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          <?php echo BOX_HEADING_EZPAGES; ?>
        </a>
        <div class="dropdown-menu mb-2" aria-labelledby="navbarDropdown">

<?php

	echo '<ul class="m-0 p-0">';
	
    $page_query = $db->Execute("select * from " . TABLE_EZPAGES . " where status_sidebox = 1 and sidebox_sort_order > 0 order by sidebox_sort_order, pages_title");
    if ($page_query->RecordCount()>0) {
      $title =  BOX_HEADING_EZPAGES;
      $box_id =  'ezpages';
      $rows = 0;
      while (!$page_query->EOF) {
        $rows++;
`

**Comment by zcadditions** [comment]
I'll take a look as time permits
