### ISSUE TITLE
Classes: Reduce core-file overwrites

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-BETA-#3]
There are a couple of core-file **_class_** overwrites currently used; this issue will track the status of changes to reduce (hopefully to zero!) that count.

- [x] /includes/classes/breadcrumb.php.  Processing now provided by /includes/classes/zca/zca_breadcrumb.php
- [x] /includes/classes/message_stack.php.  Processing now provided by /includes/classes/zca/zca_message_stack.php
- [x] /includes/classes/order.php.  One in-line marked change section.
- [x] /includes/classes/site_map.php.  Additional functions added to allow an external caller to supply the parent/child starting HTML.
- [x] /includes/classes/split_page_results.php.  Processing now provided by /includes/classes/zca/zca_split_page_results.php.

This issue will also track changes to remove the majority of the core-file overwrites in the /includes/functions and /includes/modules/pages directories.

The function files are modified, adding notifiers (acted upon by /includes/classes/observers/ZcaBootstrapObserver.php) to provide template-specific styling for the template.

Affected pages (other than `specials`) now have a header_php_zca_bootstrap*.php that provides template-specific rendering of the bootstrap template is currently installed.

**Comment by zcadditions** [comment]
@lat9 is this missing the /includes/classes/observers/ZcaBootstrapObserver.php file.

**Comment by lat9** [comment]
Sorry about that; it's there now!
