### ISSUE TITLE
Formatting issue when tagline is blank

### ISSUE THREAD

**Issue by badarac** [zcadditions/ZCA-Bootstrap-Template-BETA-#31]
This one sort of fell through the cracks. I'm reposting from my forum post. 

In includes/templates/bootstrap/common/header.php there is a test for the sales text being blank. If blank it does not include the tagline. This caused formatting problems with the header. I've looked at that again as a result of using a large width image in the header. Because the logo div is set to col-sm-4 regardless of the presence of a tagline, it shrinks the image to fit into 4 cols. There was also a problem with the location of the closing div for the logo wrapper and some line breaks that affected spacing of the header. Here's what I wound up with for the branding section: 
`
<div id="logoWrapper">
    
  <div id="logo" class="row align-items-center">
        <?php if (HEADER_SALES_TEXT != '') {
            echo '<div class="col-sm-4">';
        } else {
            echo '<div class="col-sm-12">';
            }
            ?>
        <?php echo '<a href="' . HTTP_SERVER . DIR_WS_CATALOG . '">' . zen_image($template->get_template_dir(HEADER_LOGO_IMAGE, DIR_WS_TEMPLATE, $current_page_base,'images'). '/' . HEADER_LOGO_IMAGE, HEADER_ALT_TEXT, HEADER_LOGO_WIDTH, HEADER_LOGO_HEIGHT) . '</a>'; ?>
    </div>
<?php if (HEADER_SALES_TEXT != '' || (SHOW_BANNERS_GROUP_SET2 != '' && $banner = zen_banner_exists('dynamic', SHOW_BANNERS_GROUP_SET2))) { ?>    
    <div id="taglineWrapper" class="text-center col-sm-8">
<?php
              if (HEADER_SALES_TEXT != '') {
?>
      <div id="tagline"><?php echo HEADER_SALES_TEXT;?></div>
<?php
              }
?>
<?php
              if (SHOW_BANNERS_GROUP_SET2 != '' && $banner = zen_banner_exists('dynamic', SHOW_BANNERS_GROUP_SET2)) {
                if ($banner->RecordCount() > 0) {
?>
      <div id="bannerTwo" class="banners"><?php echo zen_display_banner('static', $banner);?></div>
<?php
                }
              }
?>
    </div>
<?php } 
// no HEADER_SALES_TEXT or SHOW_BANNERS_GROUP_SET2 ?>
  </div>

</div>
`

**Comment by zcadditions** [comment]
Additional padding classes need to be added to the following fix.
