### ISSUE TITLE
cvv_help modal instructions needed

### ISSUE THREAD

**Issue by zcadditions** [zcadditions/ZCA-Bootstrap-Template-BETA-#34]
The default cvv_help modal wont initiate with 3rd party payment modules. Instructions to replace the stock zen_href_link with data-toggle="modal" should be included in install instructions when install instructions exist.

**Comment by drbyte** [comment]
Is there a way to just disable that popup altogether, for those modules that haven't accommodated BS support? 

ie: NOT touching every payment module for "just" this "feature" would be preferable.
(ie: IMO who uses the cvv popup nowadays anymore?)

**Comment by zcadditions** [comment]
As the code sits, the BS modal has no effect on modules other than the stock Authorize.net module so there is nothing to disable.

The thinking behind this was to offer instructions to offer the option to use the BS modal if one chooses too!

In order for the BS modal to work, one would have to change:
<a href="javascript:popupWindow(\'' . zen_href_link(FILENAME_POPUP_CVV_HELP) . '\')">

to:
<a data-toggle="modal" href="#cvvHelpModal">

**Comment by zcadditions** [comment]
Should remove this option from Authorize.net as well? And just include instructions to add it?

**Comment by drbyte** [comment]
I would.

I understand the original thinking, but the more I ponder it the more I think it's better to simply document it, instead of touching files that could cause other complications.

**Comment by zcadditions** [comment]
enough said...
