### ISSUE TITLE
Replace shopping cart icons w/ FA icons

### ISSUE THREAD

**Issue by drbyte** [zcadditions/ZCA-Bootstrap-Template-BETA-#47]
In mobile view, the delete button on the shopping-cart page is miniscule.

Maybe switch to an FA icon? 

<img width="425" alt="image 2018-04-23 at 3 12 46 pm" src="https://user-images.githubusercontent.com/404472/39147961-0e1ca8ca-4709-11e8-8ff4-6ef39aac49d4.png">

**Comment by zcadditions** [comment]
I am torn here!

Font Awesome is included in html_header.php but not utilized.

If I change this icon to an FA icon, should I change all icons to utilize FA icons for consistency?

or should I include custom buttons and icons for use in the template?

**Comment by Zen4All** [comment]
Go with fa.

**Comment by drbyte** [comment]
ZC's default template uses FA.

Also, FA is up to `5.0.10` as of this past weekend. (5.0.8 is currently mentioned in html_header)
