### ISSUE TITLE
Order-totals formatting is incompatible with "One Page Checkout"

### ISSUE THREAD

**Issue by lat9** [zcadditions/ZCA-Bootstrap-Template-BETA-#48]
The template provides its specialized formatting for the order-totals display (tpl_modules_order_total.php) that does not include the "standard" Zen Cart classes for the individual order-totals.  Without this information, the One-Page Checkout doesn't work.

Within that module, the opening `<tr>` for each totals' formatting should be updated to include that standard class

```
<tr id="<?php echo str_replace('_', '', $GLOBALS[$class]->code); ?>">
```

I will create/submit a PR if requested; associated OPC GitHub issue is: https://github.com/lat9/one_page_checkout/issues/118

**Comment by lat9** [comment]
Note, too, that some of the One-Page Checkout's pages are going to require some care-and-feeding from a CSS standpoint to render correctly when used with `bootstrap`.  I'm still trying to find the best way to actually get the radio-buttons for the shipping and payment selections to display.

**Comment by zcadditions** [comment]
Cindy,

When I get a moment I will download and play with......

**Comment by drbyte** [comment]
For displaying those elements, two thoughts come to mind:
Have you merged #40 with your working copy? 
Also are you able to wrap those elements with custom-control classes as ray mentioned in https://github.com/zcadditions/ZCA-Bootstrap-Template-BETA-/pull/40#issuecomment-383446760

**Comment by lat9** [comment]
I have merged #40 (although that only affected `<select>` generation) without affect.

The following is what I see on the `checkout_one` page ... none of the radio-buttons are rendering:
![image](https://user-images.githubusercontent.com/2685585/39204280-640aab9e-47c5-11e8-8e84-1a49c4b9d97b.png)

The top shipping selection's HTML is
```
<input class="custom-control-input" name="shipping" value="flat_flat" id="ship-flat-flat" type="radio">
```
... so the bootstrap class changes are being pulled in.

**Comment by zcadditions** [comment]
```
<?php
                            }
														echo '<div class="custom-control custom-radio">';
                            echo zen_draw_radio_field('shipping', $shipping_method, $checked, 'id="ship-'.$quotes[$i]['id'] . '-' . str_replace(' ', '-', $quotes[$i]['methods'][$j]['id']) .'"'); 
?>
          <label for="ship-<?php echo $quotes[$i]['id'] . '-' . str_replace(' ', '-', $quotes[$i]['methods'][$j]['id']); ?>" class="custom-control-label checkboxLabel" id="<?php echo str_replace (' ', '-', $shipping_method); ?>-title"><?php echo $quotes[$i]['methods'][$j]['title']; ?></label>
          </div>
					
					<br class="clearBoth" />
```

**Comment by lat9** [comment]
If I 'nullify' the styling on `_custom-forms.scss:22` for .custom-control-input then the radio buttons display.

**Comment by zcadditions** [comment]
You can do that but will it have the same result on other radio buttons?

Adding the wrapping div will not affect the OPC layout on NON-bootstrap themes.....

**Comment by drbyte** [comment]
Agreed: i'd expect the wrapping div to be safe.

**Comment by lat9** [comment]
I wasn't suggesting that the style be altered, just pointing to what I see as (part of) the issue's source.

**Comment by lat9** [comment]
I'm unclear as to where this "wrapping div" should be applied; are we talking in the OPC's 'shipping-choices' template?

**Comment by zcadditions** [comment]
Cindy,

I made the changes to tpl_modules_checkout_one_shipping.php which is required by tpl_modules_opc_shipping_choices.php

The changes above are to tpl_modules_checkout_one_shipping.php:37

**Comment by zcadditions** [comment]
Cindy,

I just installed this on a test site, made the above changes to 2 files and presto! I also forked and made changes in a pull request. 

You can see it live here.
http://www.zcadditions.com/bootstrap_pro2_tpl_demo/
